import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Code from "./images/Code.png"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-5 bg-zinc-900  shadow-gray-400 top fixed w-full " >
          <div className=" flex shadow-gray-400 ">
            <Image src={Code} width={30} height={30} style={{marginTop:"10px",marginLeft:"20px"}}/>
            <Link style={{marginTop:"10px",marginLeft:"25px"}}href="/">Home</Link>
            <Link style={{marginTop:"10px",marginLeft:"20px"}}href="/experience">Experience</Link>
            <Link style={{marginTop:"10px",marginLeft:"20px"}}href="/projects">Projects</Link>
            <Link style={{marginTop:"10px",marginLeft:"20px"}}href="/certificates">Certificates</Link>
            <Link style={{marginTop:"10px",marginLeft:"20px"}}href="/resume">Resume</Link>
            
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
